#!/usr/bin/env bash
# Dev-only. Compiles the dashboard's tailwind.css from the templates (no CDN at runtime).
#   ./build.sh          rebuild tracker-setup/templates/dashboard/static/tailwind.css
#   ./build.sh --check  exit 1 if it's out of date
set -euo pipefail
cd "$(dirname "$0")"
[ -x node_modules/.bin/tailwindcss ] || npm install --silent --no-audit --no-fund
OUT=../../tracker-setup/templates/dashboard/static/tailwind.css
TMP=$(mktemp); trap 'rm -f "$TMP"' EXIT
node_modules/.bin/tailwindcss -c tailwind.config.js -i input.css -o "$TMP" --minify 2>/dev/null
{ echo "/* Generated by dev/dashboard-css/build.sh from the dashboard templates. Don't edit by hand. */"; cat "$TMP"; } > "$TMP.2"
if [ "${1:-}" = "--check" ]; then
  cmp -s "$TMP.2" "$OUT" && echo "tailwind.css is up to date" || { echo "tailwind.css is out of date: run dev/dashboard-css/build.sh"; rm -f "$TMP.2"; exit 1; }
else
  mv "$TMP.2" "$OUT"; echo "wrote $OUT ($(( $(wc -c < "$OUT") / 1024 )) KB)"
fi
rm -f "$TMP.2"
