"""Dev-only, needs the internet. Downloads the dashboard's fonts once into
tracker-setup/templates/dashboard/static/ so generated dashboards load nothing
from outside: Plus Jakarta Sans (SIL OFL) and a Material Symbols
subset (Apache 2.0) with the icons the templates use, the preset icons, and a
set for other domains. Writes static/fonts.css. Re-run when the templates start
using a new icon.  python3 dev/dashboard-css/fonts.py"""
import json, re, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TPL = ROOT / "tracker-setup" / "templates" / "dashboard"
OUT = TPL / "static"; FONTS = OUT / "fonts"
UA = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36"}
EXTRA_ICONS = """home apartment house domain school handshake storefront business_center work rocket_launch travel_explore
favorite real_estate_agent sell paid savings volunteer_activism local_hospital science palette code group person
badge public map key account_balance apps category music_note restaurant fitness_center pets flight""".split()

def get(url, binary=False):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as r:
        data = r.read()
    return data if binary else data.decode()

def latin_face(css):
    block = css[css.index("/* latin */"):]
    return re.search(r"@font-face \{.*?\}", block, re.S).group(0)

def main():
    FONTS.mkdir(parents=True, exist_ok=True)
    faces = []
    # Plus Jakarta Sans throughout (the Yuan type), every weight the dashboard uses.
    for family, axis, fname in [("Plus+Jakarta+Sans", "wght@400..800", "PlusJakartaSans-latin.woff2")]:
        face = latin_face(get(f"https://fonts.googleapis.com/css2?family={family}:{axis}&display=swap"))
        url = re.search(r"url\((https://[^)]+)\)", face).group(1)
        (FONTS / fname).write_bytes(get(url, binary=True))
        faces.append(face.replace(url, f"fonts/{fname}"))
    names = set(get("https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/"
                    "MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints").split()[0::2])
    text = " ".join(p.read_text() for p in [*TPL.glob("*.j2"), ROOT / "tracker-setup/scripts/generate_project.py"])
    text += " " + " ".join(json.loads(p.read_text()).get("icon", "") for p in (ROOT / "tracker-setup/presets").glob("*.json"))
    icons = sorted((set(re.findall(r"[a-z][a-z0-9_]{2,}", text)) | set(EXTRA_ICONS)) & names)
    css = get("https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1"
              f"&icon_names={','.join(icons)}&display=block")
    url = re.search(r"url\((https://[^)]+)\)", css).group(1)
    (FONTS / "MaterialSymbolsOutlined-subset.woff2").write_bytes(get(url, binary=True))
    faces.append(css.replace(url, "fonts/MaterialSymbolsOutlined-subset.woff2").strip())
    (OUT / "fonts.css").write_text("/* Generated by dev/dashboard-css/fonts.py. Local fonts only; licences in fonts/. */\n"
                                   f"/* Icons in the subset ({len(icons)}): {' '.join(icons)} */\n" + "\n".join(faces) + "\n")
    for name, url in [("OFL-PlusJakartaSans.txt", "https://raw.githubusercontent.com/google/fonts/main/ofl/plusjakartasans/OFL.txt"),
                      ("LICENSE-MaterialSymbols.txt", "https://raw.githubusercontent.com/google/material-design-icons/master/LICENSE")]:
        (FONTS / name).write_text(get(url))
    print(f"{len(icons)} icons; " + ", ".join(f"{p.name} {p.stat().st_size // 1024} KB" for p in sorted(FONTS.iterdir())))

if __name__ == "__main__":
    main()
