"""Embeds the tracker-setup skill (and its intake schema) into the setup page,
so the page can put it in the download without fetching anything.

    python3 portal/build.py          write portal/skill-bundle.js
    python3 portal/build.py --check  exit 1 if skill-bundle.js is out of date

Run it whenever anything under tracker-setup/ changes. Examples and caches
are left out; everything else is copied as text.
"""
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "tracker-setup"
OUT = REPO / "portal" / "skill-bundle.js"
SKIP_DIRS = {"__pycache__", "examples"}
SKIP_FILES = {".DS_Store"}


def render() -> str:
    files = {}
    for path in sorted(SRC.rglob("*")):
        rel = path.relative_to(SRC)
        if path.is_dir() or SKIP_DIRS & set(rel.parts) or path.name in SKIP_FILES or path.suffix == ".pyc":
            continue
        files[rel.as_posix()] = path.read_text(encoding="utf-8")
    digest = hashlib.sha256(json.dumps(files, sort_keys=True).encode()).hexdigest()[:10]
    bundle = {"version": digest, "schema": json.loads(files["intake.schema.json"]), "files": files}
    return ("/* Generated by portal/build.py from tracker-setup/. Don't edit by hand. */\n"
            "window.JST_BUNDLE = " + json.dumps(bundle, ensure_ascii=False, separators=(",", ":")) + ";\n")


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("portal/skill-bundle.js is out of date: run python3 portal/build.py")
            sys.exit(1)
        print("portal/skill-bundle.js is up to date")
    else:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(REPO)} ({len(text) // 1024} KB, {text.count(chr(34) + ':' + chr(34))} entries)")
